version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  app-db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret

  ws:
    image: ghcr.io/bitomic/ws-wikiactivity:1.0.0.42
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - ws-redis
    environment:
      PORT: 3001
      REDIS_HOST: ws-redis
      REDIS_PASS: chaeyoung

  ws-redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass chaeyoung

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  